
# Do not add "/" at the end of paths.
directories:
  inputs: "data"

  results: "results"
  trim_fastq:   "results/01_trim/fastq"
  trim_reports: "results/01_trim/reports"
  consensus_fasta:   "results/02_consensus/fasta"
  consensus_reports: "results/02_consensus/reports"
  blast_raw: "results/03_blast/raw_hits"
  summary: "results/summary"

parameters:
  trim_cutoff: 0.05

